version: '3'

services:
  # localstack:
  #   image: 'localstack/localstack:0.13.0'
  #   restart: always
  #   environment:
  #     - AWS_DEFAULT_REGION=sa-east-1
  #     - SERVICES=dynamodb
  #   ports:
  #     - "4566-4599:4566-4599"
  #     - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
  #   volumes:
  #     - ./docker/aws:/docker-entrypoint-initaws.d

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml"

  grafana:
    image: grafana/grafana
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - "./docker/volumes/grafana:/var/lib/grafana:rw"

  etcd:
    image: 'bitnami/etcd:3.5.2'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2379"]
      interval: 30s
      timeout: 10s
      retries: 5

  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   deploy:
  #     resources:
  #       reservations:
  #         cpus: 0.5
  #         memory: 512M
  #       limits:
  #         cpus: 1
  #         memory: 1024M
  #   restart: on-failure
  #   depends_on:
  #     - etcd
  #   links:
  #     - etcd
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost8080/metrics"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
