etcd:
  server_endpoints:
    - etcd:2379
redis:
  server_address: redis:6379
  password: 123456
opentelemetry:
  agent_host: jaeger
  agent_port: 6831
app:
  name: "Router"
  server_address: 0.0.0.0:8080
