etcd:
  server_endpoints:
    - localhost:2379
redis:
  server_address: localhost:6379
  password: 123456
opentelemetry:
  agent_host: localhost
  agent_port: 6831
aws:
  region: "sa-east-1"
  endpoint_url: http://localhost:4566
  sns:
    health_topic_arn: arn:aws:sns:sa-east-1:000000000000:health-cells-topic
  sqs:
    health_queue_url: http://localhost:4566/000000000000/health-cells-queue

app:
  name: Router
  server_address: 0.0.0.0:8080
