etcd:
  server_endpoints:
    - etcd:2379
redis:
  server_address: redis:6379
  password: 123456
opentelemetry:
  agent_host: jaeger
  agent_port: 6831
aws:
  region: "sa-east-1"
  endpoint_url: http://localstack:4566
  sns:
    health_topic_arn: arn:aws:sns:sa-east-1:000000000000:health-cells-topic
  sqs:
    health_queue_url: http://localstack:4566/000000000000/health-cells-queue
servers:
  -
    server_name: Server 1
    service_prefix: app1
    endpoint_url: http://dummy-app1:8080
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://dummy-app1:8081/actuator/health
  -
    server_name: Server 2
    service_prefix: app2
    endpoint_url: http://dummy-app2:8080
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://dummy-app3:8081/actuator/health
  -
    server_name: Server 3
    service_prefix: app3
    endpoint_url: http://dummy-app3:8080
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://dummy-app3:8081/actuator/health
app:
  name: "Router"
  server_address: 0.0.0.0:8080
