etcd:
  server_endpoints:
    - localhost:2379
redis:
  server_address: localhost:6379
  password: 123456
opentelemetry:
  agent_host: localhost
  agent_port: 6831
aws:
  region: sa-east-1
  endpoint_url: http://localhost:4566
  sns:
    health_topic_arn: arn:aws:sns:sa-east-1:000000000000:health-cells-topic
  sqs:
    health_queue_url: http://localhost:4566/000000000000/health-cells-queue
servers:
  -
    server_name: Server 1
    service_prefix: app1
    endpoint_url: http://localhost:8081
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://localhost:8081/actuator/health
  -
    server_name: Server 2
    service_prefix: app2
    endpoint_url: http://localhost:8082
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://localhost:8082/actuator/health
  -
    server_name: Server 3
    service_prefix: app1
    endpoint_url: http://localhost:8083
    zone_aws: sa-east-1a
    alive: true
    healthcheck:
      type: http
      endpoint: http://localhost:8083/actuator/health
app:
  name: Router
  server_address: 0.0.0.0:8080
